### PR TITLE
Add german translation

### PR DESCRIPTION
**Pull request by jamal2362**
* Translated and tested.

### CODE REVIEW

**Comment by Rocky5** [comment]
Can you translate these also. These are in the next update coming shortly. 

line: 474 for this

msgctxt "#31162"
msgid "XBMC4Gamers Options"
msgstr "Change Me!"


These go at the end of the file:


msgctxt "#31606"
msgid "Warning"
msgstr "Change Me!"

msgctxt "#31607"
msgid "This will reset all XBMC4Gamers options.[CR]Main settings are not reset."
msgstr "Change Me!"

msgctxt "#31608"
msgid "Settings reset, will now reload the profile[CR]to complete the process."
msgstr "Change Me!"

**Comment by jamal2362** [comment]
Done! 🙂​

**Comment by Rocky5** [comment]
Thank you.

**Comment by jamal2362** [comment]
No problem. 
Thanks for your work!

**Pull request merged**
